import type { Metadata } from 'next';
import { date, disabledParkingTagStatus, getVehicleReport, groupOwnership, parsePlate, value, yesNo, type Row, type VehicleReport, type VehicleStatus } from '@/lib/vehicles';
import { siteUrl } from '@/lib/site';

export async function generateMetadata({ searchParams }: { searchParams: Promise<{ plate?: string | string[] }> }): Promise<Metadata> {
  return (await searchParams).plate !== undefined
    ? { robots: { index: false, follow: true }, alternates: { canonical: '/' } }
    : { alternates: { canonical: '/' } };
}

function Cell({ label, children }: { label: string; children: React.ReactNode }) { return <div className="cell"><span>{label}</span><strong>{children}</strong></div>; }
function Section({ id, icon, title, subtitle, children }: { id: string; icon: string; title: string; subtitle?: string; children: React.ReactNode }) { return <section className="card" id={id}><div className="cardHead"><div className="cardTitle"><span className="sectionIcon" aria-hidden="true">{icon}</span><div><h2>{title}</h2>{subtitle && <p>{subtitle}</p>}</div></div></div>{children}</section>; }
function Status({ error, found, empty = 'לא נמצא מידע במאגר זה' }: { error: boolean; found: boolean; empty?: React.ReactNode }) { if (error) return <p className="notice warning">מאגר הנתונים אינו זמין כרגע. כדאי לנסות שוב מאוחר יותר.</p>; if (!found) return <p className="notice">{empty}</p>; return null; }
function Details({ row, fields }: { row: Row | null; fields: [string, string][] }) { return <div className="details">{fields.map(([key, label]) => <Cell key={key} label={label}>{value(row, key)}</Cell>)}</div>; }
function fmtNumber(n: unknown) { return typeof n === 'number' ? new Intl.NumberFormat('he-IL').format(n) : n ? String(n) : 'לא זמין'; }
function vehicleTitle(row: Row | null): string {
  if (!row) return 'בדיקת רכב';
  return [row.tozeret_nm, row.kinuy_mishari || row.degem_nm].filter(Boolean).join(' ') || 'בדיקת רכב';
}
const statusLabels: Record<VehicleStatus, string> = {
  active: 'רשומה במאגר הפעילים', inactive: 'רשומה במאגר הלא פעילים', canceled: 'נמצאה רשומת ביטול סופי',
  unknown: 'לא נקבע סטטוס', unavailable: 'חלק מהמאגרים אינם זמינים',
};
function SummaryItem({ label, main, detail, tone = 'neutral' }: { label: string; main: string; detail: string; tone?: 'neutral' | 'warning' | 'danger' }) {
  return <div className={`summaryItem ${tone}`}><span>{label}</span><strong>{main}</strong><small>{detail}</small></div>;
}
function ReportSummary({ report }: { report: VehicleReport }) {
  const statusTone = report.status === 'canceled' ? 'danger' : report.status === 'inactive' || report.status === 'unavailable' ? 'warning' : 'neutral';
  return <section className="summaryPanel" aria-label="סיכום הבדיקה"><div className="summaryPanelHead"><div><span className="eyebrow small">במבט אחד</span><h3>סיכום הבדיקה</h3></div><p>מציג מה פורסם במאגרים שנבדקו; מידע חסר אינו אישור לתקינות.</p></div><div className="summaryGrid">
    <SummaryItem label="רישום הרכב" main={statusLabels[report.status]} detail={report.status === 'active' ? 'נמצא במאגר הרכב הפעיל' : report.status === 'inactive' ? 'יש לאמת מצב עדכני מול משרד התחבורה' : report.status === 'canceled' ? 'נדרש בירור מול משרד התחבורה' : 'לא ניתן להסיק שהרכב פעיל'} tone={statusTone}/>
    <SummaryItem label="תוקף רישוי במאגר" main={report.base?.tokef_dt ? date(report.base.tokef_dt) : 'לא זמין'} detail="התאריך המדווח, לא אישור רישוי עדכני"/>
    <SummaryItem label="נסועה בטסט האחרון" main={report.history?.kilometer_test_aharon != null ? `${fmtNumber(report.history.kilometer_test_aharon)} ק״מ` : report.errors.history ? 'המאגר לא זמין' : 'לא פורסמה רשומה'} detail="מדידה אחת בלבד, אם קיימת" tone={report.errors.history ? 'warning' : 'neutral'}/>
    <SummaryItem label="היסטוריית בעלות" main={report.ownership.length ? `${report.ownership.length} רשומות מקור` : report.errors.ownership ? 'המאגר לא זמין' : 'לא פורסמה רשומה'} detail="רשומות זהות מוצגות יחד; זה אינו מספר בעלים" tone={report.errors.ownership ? 'warning' : 'neutral'}/>
    <SummaryItem label="ריקולים שלא בוצעו" main={report.openRecalls.length ? `${report.openRecalls.length} רשומות` : report.errors.openRecalls ? 'המאגר לא זמין' : 'לא נמצאה רשומה'} detail="יש לוודא גם מול היבואן" tone={report.openRecalls.length ? 'danger' : report.errors.openRecalls ? 'warning' : 'neutral'}/>
    <SummaryItem label="תג חניה לנכה" main={disabledParkingTagStatus(report)} detail="רישום במאגר לפי מספר רכב; לא זכאות הקונה" tone={report.errors.disabledParkingTag ? 'warning' : 'neutral'}/>
  </div></section>;
}
function PurchaseChecklist() {
  return <section className="checklist card" id="checklist"><div className="cardHead"><div className="cardTitle"><span className="sectionIcon" aria-hidden="true">✓</span><div><h2>לפני שקונים את הרכב</h2><p>בדיקות שכדאי להשלים מחוץ ל־AUTOPEEK</p></div></div></div><ol>
    <li><div><strong>השוו לרישיון הרכב</strong><p>בדקו שמספר הרישוי, מספר השלדה ופרטי הרכב תואמים למסמכים ולרכב עצמו.</p></div></li>
    <li><div><strong>בדקו דיווח על גניבה</strong><p>בצעו בדיקה בשירות משטרת ישראל. גם תוצאה ללא דיווח אינה אישור מוחלט למצב הרכב.</p><a href="https://www.gov.il/apps/police/stolencar/" target="_blank" rel="noopener noreferrer">לבדיקה באתר המשטרה ↗</a></div></li>
    <li><div><strong>בררו שעבודים ומשכונות</strong><p>בדקו מול שירות רשות התאגידים. בהתאם לסוג הבעלות ייתכן שצריך לעיין גם בשעבוד וגם במשכון.</p><a href="https://www.gov.il/he/service/pawn_perusal" target="_blank" rel="noopener noreferrer">לשירות העיון הרשמי ↗</a></div></li>
    <li><div><strong>אמתו ריקולים ותקינות</strong><p>בררו מול היבואן אם קיימת קריאה חוזרת, ובצעו בדיקה מקצועית לפני קבלת החלטה.</p><a href="https://www.gov.il/he/Departments/DynamicCollectors/cars-recall?skip=0" target="_blank" rel="noopener noreferrer">למידע על ריקולים ↗</a></div></li>
  </ol></section>;
}

export default async function Home({ searchParams }: { searchParams: Promise<{ plate?: string | string[] }> }) {
  const supplied = (await searchParams).plate;
  const raw = typeof supplied === 'string' && supplied.length <= 12 ? supplied.trim() : '';
  const plate = parsePlate(raw);
  const invalid = supplied !== undefined && !plate;
  const report = plate && !invalid ? await getVehicleReport(plate) : null;
  const ownershipGroups = report ? groupOwnership(report.ownership) : [];
  const vehicle = report?.base ?? null;
  const model = report?.model[0] ?? null;
  const price = report?.prices[0] ?? null;
  const hasResult = Boolean(report && (vehicle || report.history || report.openRecalls.length || report.ownership.length || report.disabledParkingTag));
  return <>
    {!report && <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify({
      '@context': 'https://schema.org', '@type': 'WebSite', name: 'AUTOPEEK', url: siteUrl.toString(),
      inLanguage: 'he-IL', description: 'בדיקת רכב בישראל לפי מספר רישוי באמצעות מידע ממאגרים ציבוריים.',
    }) }}/>}
    <header className="topbar"><div className="topbarInner"><a className="brand" href="/" aria-label="AUTOPEEK — דף הבית"><span className="brandMark">A<span>•</span></span><span>AUTO<span className="brandAccent">PEEK</span></span></a><nav className="topLinks" aria-label="ניווט ראשי"><a className="topLink" href="/compare">השוואת רכבים</a><a className="topLink" href="/garages">מוסכים מורשים</a><a className="topLink" href="/appraisers">שמאי רכב</a><a className="topLink" href="/guide">מדריך</a></nav></div></header>
    <main id="main-content" tabIndex={-1} className="pageWrap">
      <section className={`hero${report ? ' heroCompact' : ''}`}><h1>{report ? <>בדיקת רכב <em>במספר רישוי</em></> : <>בדיקת רכב לפי <em>מספר רישוי</em><br/>לפני שמחליטים</>}</h1>
        {!report && <p className="heroText">בדקו מה פורסם על הרכב במאגרים ציבוריים בישראל לפני קנייה או מכירה. החיפוש חינם, ללא הרשמה.</p>}
        <form className="searchBox" action="/" method="get"><div className="searchInput"><span className="searchIcon" aria-hidden="true">⌕</span><input name="plate" type="text" inputMode="numeric" pattern="[0-9\- ]{5,12}" maxLength={12} autoComplete="off" placeholder="הקלידו מספר רישוי" defaultValue={raw} aria-label="מספר רישוי" aria-invalid={invalid || undefined} aria-describedby={invalid ? "plate-error" : undefined} required/></div><button type="submit">בדיקת רכב <span>←</span></button></form>
        {invalid && <p className="formError" id="plate-error" role="alert">יש להזין מספר רישוי ישראלי בן 5 עד 8 ספרות.</p>}
        {!report && <div className="heroNote"><span aria-hidden="true">✦</span> חיפוש חינם <i/> ללא הרשמה <i/> דוח להורדה</div>}
        <a className="compareEntry" href={plate ? `/compare?first=${encodeURIComponent(plate)}` : '/compare'}>{report ? 'השוו את הרכב הזה לרכב נוסף ←' : 'מתלבטים בין שני רכבים? השוו ביניהם ←'}</a>
      </section>
      {!report && <><div className="sectionLead"><span>מה אפשר לבדוק?</span><h2>תמונה מלאה יותר על הרכב</h2><p>חיפוש אחד מרכז נתונים ממספר מאגרים ממשלתיים.</p></div><div className="featureGrid"><div><span aria-hidden="true">▤</span><h3>פרטי הרכב</h3><p>יצרן, דגם, שנת ייצור, דלק, צבע, צמיגים ותוקף רישוי</p></div><div><span aria-hidden="true">◷</span><h3>היסטוריה ובעלות</h3><p>נסועה בטסט האחרון, שינויי מבנה ותאריכי בעלות</p></div><div><span aria-hidden="true">◈</span><h3>ריקולים וסטטוס</h3><p>קריאות שירות שלא בוצעו, ביטול סופי ורישום לתג חניה לנכה</p></div><div><span aria-hidden="true">⌁</span><h3>נתוני דגם</h3><p>מפרט ונתוני WLTP, לצד מחיר יבואן לרכב חדש</p></div></div><section className="homeFaq" aria-labelledby="home-faq-title"><div className="homeFaqHead"><span className="eyebrow small">לפני שקונים</span><h2 id="home-faq-title">שאלות נפוצות על בדיקת רכב</h2></div><div className="homeFaqGrid"><article><h3>מה אפשר לראות לפי מספר רישוי?</h3><p>נתוני רישום, פרטי רכב, תוקף רישוי מדווח, נסועה מהטסט האחרון, סוגי בעלות וריקולים שלא בוצעו, ככל שקיימת רשומה בכל מאגר. <a href="/guide/mileage">מה אומר נתון הקילומטראז׳?</a></p></article><article><h3>האם היעדר רשומה אומר שהרכב תקין?</h3><p>לא. הכיסוי משתנה בין מאגרים, ועדכון המידע עשוי להתעכב. תוצאה ללא ריקול או ללא היסטוריית בעלות אינה אישור רשמי. <a href="/guide/recalls">איך בודקים ריקול?</a></p></article><article><h3>האם זו בדיקה מספקת לפני קנייה?</h3><p>לא. כדאי להשוות לרישיון הרכב, לבדוק דיווח גניבה ושעבודים בשירותים הרשמיים, ולבצע בדיקה מקצועית.</p></article></div><a className="guideLink" href="/guide">למדריך המלא לבדיקת רכב לפני קנייה ←</a></section></>}
      {report && <div className="results" id="results">
        <div className="resultsHeader"><div><span className="eyebrow small">דוח רכב</span><h2>{vehicleTitle(vehicle)}</h2><p>מידע ציבורי לפי מספר הרישוי שהוזן. הנתונים עשויים להיות חלקיים או להתעדכן במקור.</p></div><div className="plateBadge"><span>IL</span><strong dir="ltr">{plate}</strong></div></div>
        {hasResult && <ReportSummary report={report}/>}
        {hasResult && <div className="reportToolbar"><nav className="reportNav" aria-label="ניווט בדוח"><a href="#vehicle">פרטי הרכב</a><a href="#history">נסועה</a><a href="#ownership">בעלות</a><a href="#recalls">ריקולים</a><a href="#parking-tag">תג חניה לנכה</a><a href="#status">סטטוס</a><a href="#checklist">לפני קנייה</a></nav><a className="downloadButton" href={`/api/report?plate=${encodeURIComponent(plate!)}`} download={`AUTOPEEK-${plate}.pdf`}>↓ הורדת דוח PDF</a></div>}
        {!hasResult && <div className="card emptyState"><h2>{report.status === 'unavailable' ? 'חלק ממאגרי המידע אינם זמינים כרגע' : 'לא נמצאו נתונים למספר הזה'}</h2><p>{report.status === 'unavailable' ? 'אי אפשר לקבוע את מצב הרכב כעת. נסו שוב מאוחר יותר.' : 'ייתכן שהרכב מחוץ לטווח הכיסוי של המאגרים, או שמספר הרישוי אינו נכון. היעדר רשומה אינו אישור למצב הרכב.'}</p></div>}
        {hasResult && <>
          {report.canceled && <div className="alert danger"><span aria-hidden="true">!</span><div><strong>נמצאה רשומה של ביטול סופי</strong><p>תאריך ביטול: {date(report.canceled.bitul_dt)}. יש לאמת סטטוס עדכני מול משרד התחבורה.</p></div></div>}
          {report.status === 'inactive' && <div className="alert amber"><span aria-hidden="true">!</span><div><strong>הרכב מופיע במאגר רכב לא פעיל</strong><p>יש לאמת את מצב הרישוי העדכני מול משרד התחבורה לפני רכישה או שימוש ברכב.</p></div></div>}
          {report.openRecalls.length > 0 && <div className="alert amber"><span aria-hidden="true">!</span><div><strong>{report.openRecalls.length} קריאות שירות מופיעות במאגר ריקולים שלא בוצעו</strong><p>כדאי לפנות ליבואן או למוסך מורשה לבירור ולטיפול.</p></div></div>}
          <div className="resultGrid"><div className="mainColumn">
            <Section id="vehicle" icon="▤" title="פרטי הרכב" subtitle="נתונים לפי מספר רישוי"><Status error={report.errors.vehicle && !vehicle} found={!!vehicle}/>{vehicle && <><Details row={vehicle} fields={report.baseSource === 'inactiveWithoutModel' ? [["tozeret_nm","יצרן"],["degem_nm","דגם"],["shnat_yitzur","שנת ייצור"],["sug_delek_nm","סוג דלק"],["nefach_manoa","נפח מנוע (סמ״ק)"],["hanaa_nm","הנעה"]] : [["tozeret_nm","יצרן"],["kinuy_mishari","שם מסחרי"],["degem_nm","קוד דגם"],["shnat_yitzur","שנת ייצור"],["ramat_gimur","רמת גימור"],["tzeva_rechev","צבע"],["sug_delek_nm","סוג דלק"],["baalut","סוג בעלות נוכחית"],["zmig_kidmi","צמיג קדמי"],["zmig_ahori","צמיג אחורי"],["moed_aliya_lakvish","עלייה לכביש"],["kvutzat_zihum","קבוצת זיהום"],["ramat_eivzur_betihuty","רמת אבזור בטיחותי"]]}/>{(vehicle.mivchan_acharon_dt || vehicle.tokef_dt) && <div className="details"><Cell label="מועד טסט אחרון">{date(vehicle.mivchan_acharon_dt)}</Cell><Cell label="תוקף רישוי">{date(vehicle.tokef_dt)}</Cell></div>}{report.extra && <div className="subblock"><h3>פרטים נוספים</h3><Details row={report.extra} fields={[["kod_omes_tzmig_kidmi","קוד עומס צמיג קדמי"],["kod_omes_tzmig_ahori","קוד עומס צמיג אחורי"],["kod_mehirut_tzmig_kidmi","קוד מהירות קדמי"],["kod_mehirut_tzmig_ahori","קוד מהירות אחורי"],["grira_nm","אבזור גרירה"]]}/></div>}</>}</Section>
            <Section id="history" icon="◷" title="נסועה ושינויי מבנה" subtitle="הנסועה דווחה בטסט האחרון בלבד"><Status error={report.errors.history} found={!!report.history} empty={<>לא פורסמה לרכב זה רשומה במאגר ההיסטוריה, ולכן אין לנו נתון נסועה או שינויי מבנה ממנו.{vehicle?.mivchan_acharon_dt && <> מועד הטסט האחרון במאגר הרכב: {date(vehicle.mivchan_acharon_dt)}.</>}</>}/>{report.history && <><div className="mileage"><span>נסועה בטסט האחרון</span><strong>{fmtNumber(report.history.kilometer_test_aharon)} <small>ק״מ</small></strong></div><div className="details"><Cell label="תאריך רישום ראשון">{date(report.history.rishum_rishon_dt)}</Cell><Cell label="מקוריות">{value(report.history, 'mkoriut_nm')}</Cell><Cell label="שינוי מבנה">{yesNo(report.history.shinui_mivne_ind)}</Cell><Cell label="גפ״מ">{yesNo(report.history.gapam_ind)}</Cell><Cell label="שינוי צבע">{yesNo(report.history.shnui_zeva_ind)}</Cell><Cell label="שינוי צמיגים">{yesNo(report.history.shinui_zmig_ind)}</Cell></div><p className="finePrint">זהו נתון יחיד מהטסט האחרון, ולא היסטוריית טיפולים או רצף מדידות נסועה.</p></>}</Section>
            <Section id="ownership" icon="♙" title="היסטוריית בעלות" subtitle="חודש רישום וסוג בעלות; ללא שמות בעלים"><Status error={report.errors.ownership} found={report.ownership.length > 0} empty={<>לא פורסמה לרכב זה רשומת היסטוריית בעלות.{vehicle?.baalut && <> סוג הבעלות הנוכחית במאגר הרכב: {value(vehicle, 'baalut')}.</>} אין מכך להסיק שלא היו בעלים קודמים.</>}/>{ownershipGroups.length > 0 && <><div className="timeline">{ownershipGroups.map((group,i)=><div className="timelineItem" key={`${group.month}-${group.kind}-${i}`}><span className="timelineDot"/><div><strong>{group.kind}</strong><small>דווח לחודש {date(group.month)}</small>{group.count > 1 && <small className="timelineDuplicate">{group.count} רשומות זהות במקור</small>}</div></div>)}</div>{ownershipGroups.some(group => group.count > 1) && <p className="finePrint">רשומות עם אותו חודש ואותו סוג בעלות מוצגות יחד. אין בנתונים די מידע לקבוע אם אלו כפילויות טכניות או העברות נפרדות.</p>}</>}</Section>
            <Section id="recalls" icon="◈" title="ריקולים שלא בוצעו" subtitle="רשומות פתוחות המופיעות במאגר לפי מספר רכב"><Status error={report.errors.openRecalls} found={report.openRecalls.length > 0} empty="לא נמצאה רשומה במאגר ריקולים שלא בוצעו. היעדר רשומה אינו אישור שאין ריקול אחר."/>{report.openRecalls.map((r,i)=><article className="recall" key={`${r.RECALL_ID}-${i}`}><div><span className="tag">{value(r,'SUG_RECALL')}</span><small>{date(r.TAARICH_PTICHA)}</small></div><h3>{value(r,'SUG_TAKALA')}</h3><p>{value(r,'TEUR_TAKALA')}</p><small>מספר קריאה: {value(r,'RECALL_ID')}</small></article>)}</Section>
          </div><aside className="sideColumn">
            <Section id="parking-tag" icon="♿" title="תג חניה לנכה" subtitle="התאמה למאגר הרכבים המורשים לשאת תג"><p className={`registryStatus ${report.errors.disabledParkingTag ? 'unavailable' : ''}`}><strong>{disabledParkingTagStatus(report)}</strong></p><p className="finePrint">{report.disabledParkingTag ? 'מספר הרישוי מופיע במאגר משרד התחבורה. התג אישי לבעל הזכאות ואינו חלק מהרכב הנמכר.' : report.errors.disabledParkingTag ? 'המאגר לא היה זמין בעת הבדיקה; לא ניתן לקבוע אם הרכב מופיע בו.' : 'מספר הרישוי לא נמצא במאגר שנבדק. היעדר רשומה אינו אישור שאין תג תקף.'}</p><p className="finePrint">המאגר מציג שיוך רכב לתג, לא מידע על זהות או מצב רפואי של בעל הזכאות.</p></Section>
            <Section id="status" icon="◇" title="סטטוס במאגרים" subtitle="פרשנות לרשומה שנמצאה, לא אישור רישוי"><div className={`registryStatus ${report.status}`}><strong>{statusLabels[report.status]}</strong><p>{report.status === 'active' ? 'הרכב נמצא במאגר הרכבים הפעילים. אין בכך אישור על תקינותו, זכויות בו או היעדר מגבלות.' : report.status === 'inactive' ? 'הרכב נמצא במאגר רכבים לא פעילים. לפי הגדרת המאגר מדובר ברכבים חסרי תוקף במשך 13 חודשים, שלא סווגו בו כגנובים או כמבוטלים סופית; אין בכך אישור למצב הרכב כעת.' : report.status === 'canceled' ? `נמצאה רשומת ביטול סופי מתאריך ${date(report.canceled?.bitul_dt)}. יש לאמת את המצב במשרד התחבורה.` : report.status === 'unavailable' ? 'לפחות אחד ממאגרי הסטטוס לא היה זמין. אי אפשר לקבוע מצב מתוך הבדיקה הזו.' : 'לא נמצאה רשומה במאגרי הרכב שנבדקו. ייתכן שהרכב אינו מכוסה; אי אפשר לקבוע את מצבו.'}</p></div></Section>
            <Section id="model" icon="⌁" title="מפרט דגם ו־WLTP" subtitle="התאמה לפי קוד יצרן, קוד דגם ושנת ייצור"><Status error={report.errors.model} found={!!model}/>{model && <><Details row={model} fields={[["nefah_manoa","נפח מנוע (סמ״ק)"],["koah_sus","כוח סוס"],["mispar_moshavim","מושבים"],["merkav","מרכב"],["hanaa_nm","הנעה"],["technologiat_hanaa_nm","טכנולוגיית הנעה"],["CO2_WLTP","פליטת CO₂ WLTP (גרם/ק״מ)"],["madad_yarok","מדד ירוק"],["nikud_betihut","ציון בטיחות"]]}/><p className="finePrint">נתוני דגם עשויים להשתנות בין רמות גימור. מוצגת רשומת ההתאמה הראשונה.</p></>}</Section>
            <Section id="price" icon="₪" title="מחיר יבואן" subtitle="מחיר רכב חדש בעת דיווח היבואן"><Status error={report.errors.prices} found={!!price}/>{price && <><div className="price">₪{fmtNumber(price.mehir)}</div><p className="finePrint">{value(price,'shem_yevuan')} · שנת דגם {value(price,'shnat_yitzur')}. זה אינו שווי השוק של רכב משומש.</p></>}</Section>
            <div className="sideHint"><span aria-hidden="true">ⓘ</span><p>הודעות היצרנים על ריקולים אינן מקושרות ישירות למספר רישוי במאגר הציבורי. היעדר רשומה כאן אינו אישור שאין קריאת שירות לרכב.</p></div>
          </aside></div>
        </>}
        <PurchaseChecklist/>
      </div>}
      <section id="about" className="about"><div><span className="eyebrow small">לפני שמסתמכים על הדוח</span><h2>המידע עוזר לבדוק.<br/>הוא לא מחליף בדיקה.</h2></div><div><p>AUTOPEEK הוא שירות עצמאי המציג נתונים ממאגרים ציבוריים של משרד התחבורה. הוא אינו אתר ממשלתי ואינו פועל מטעם המדינה. זמינות הרשומות, דיוקן ומועד עדכונן תלויים במאגרים המקוריים.</p><p>היעדר רשומה אינו אישור לכך שאין ריקול, תאונה, שעבוד, בעלים קודמים או בעיה ברכב. לפני קנייה או החלטה כספית יש לאמת את הנתונים מול הגורמים המוסמכים ולבצע בדיקה מקצועית. דוח PDF משקף את המידע שהתקבל בזמן הפקתו בלבד.</p></div></section>
    </main><footer><div className="footerInner"><div className="footerBrand"><strong>AUTOPEEK</strong><span>© 2026 · שירות מידע עצמאי לרכב</span></div><nav className="footerLinks" aria-label="קישורי האתר"><a href="/compare">השוואת רכבים</a><a href="/garages">מוסכים מורשים</a><a href="/appraisers">שמאי רכב</a><a href="/guide">מדריך לבדיקה</a><a href="/terms">תנאי שימוש</a><a href="/privacy">פרטיות</a><a href="/accessibility">נגישות</a><a href="/contact">יצירת קשר</a></nav><p className="footerSource">מקור הנתונים: <a href="https://data.gov.il/he/organizations/ministry_of_transport" target="_blank" rel="noopener noreferrer">מאגרי משרד התחבורה באתר data.gov.il ↗</a></p></div></footer>
  </>;
}
