import { date, getVehicleReport, parsePlate, value, yesNo, type Row } from '@/lib/vehicles';

function Cell({ label, children }: { label: string; children: React.ReactNode }) { return <div className="cell"><span>{label}</span><strong>{children}</strong></div>; }
function Section({ id, icon, title, subtitle, children }: { id: string; icon: string; title: string; subtitle?: string; children: React.ReactNode }) { return <section className="card" id={id}><div className="cardHead"><div className="cardTitle"><span className="sectionIcon">{icon}</span><div><h2>{title}</h2>{subtitle && <p>{subtitle}</p>}</div></div></div>{children}</section>; }
function Status({ error, found, empty = 'לא נמצא מידע במאגר זה' }: { error: boolean; found: boolean; empty?: React.ReactNode }) { if (error) return <p className="notice warning">מאגר הנתונים אינו זמין כרגע. כדאי לנסות שוב מאוחר יותר.</p>; if (!found) return <p className="notice">{empty}</p>; return null; }
function Details({ row, fields }: { row: Row | null; fields: [string, string][] }) { return <div className="details">{fields.map(([key, label]) => <Cell key={key} label={label}>{value(row, key)}</Cell>)}</div>; }
function fmtNumber(n: unknown) { return typeof n === 'number' ? new Intl.NumberFormat('he-IL').format(n) : n ? String(n) : 'לא זמין'; }

export default async function Home({ searchParams }: { searchParams: Promise<{ plate?: string | string[] }> }) {
  const supplied = (await searchParams).plate;
  const raw = typeof supplied === 'string' && supplied.length <= 12 ? supplied.trim() : '';
  const plate = parsePlate(raw);
  const invalid = supplied !== undefined && !plate;
  const report = plate && !invalid ? await getVehicleReport(plate) : null;
  const vehicle = report?.base ?? null;
  const model = report?.model[0] ?? null;
  const price = report?.prices[0] ?? null;
  const hasResult = Boolean(report && (vehicle || report.history || report.openRecalls.length || report.ownership.length));
  return <main>
    <header className="topbar"><div className="topbarInner"><a className="brand" href="/" aria-label="AUTOPEEK — דף הבית"><span className="brandMark">A<span>•</span></span><span>AUTO<span className="brandAccent">PEEK</span></span></a><a className="topLink" href="#about">איך לקרוא את המידע <span>↙</span></a></div></header>
    <div className="pageWrap">
      <section className={`hero${report ? ' heroCompact' : ''}`}><h1>{report ? <>בדיקת רכב <em>במספר רישוי</em></> : <>מגלים יותר על הרכב<br/><em>לפני שמחליטים.</em></>}</h1>
        <form className="searchBox" action="/" method="get"><div className="searchInput"><span className="searchIcon">⌕</span><input name="plate" type="text" inputMode="numeric" pattern="[0-9\- ]{5,12}" maxLength={12} autoComplete="off" placeholder="הקלידו מספר רישוי" defaultValue={raw} aria-label="מספר רישוי" required/></div><button type="submit">בדיקת רכב <span>←</span></button></form>
        {invalid && <p className="formError">יש להזין מספר רישוי ישראלי בן 5 עד 8 ספרות.</p>}
        {!report && <div className="heroNote"><span>✦</span> חיפוש חינם <i/> ללא הרשמה <i/> דוח להורדה</div>}
      </section>
      {!report && <><div className="sectionLead"><span>מה אפשר לבדוק?</span><h2>תמונה מלאה יותר על הרכב</h2><p>חיפוש אחד מרכז נתונים ממספר מאגרים ממשלתיים.</p></div><div className="featureGrid"><div><span>▤</span><h3>פרטי הרכב</h3><p>יצרן, דגם, שנת ייצור, דלק, צבע, צמיגים ותוקף רישוי</p></div><div><span>◷</span><h3>היסטוריה ובעלות</h3><p>נסועה בטסט האחרון, שינויי מבנה ותאריכי בעלות</p></div><div><span>◈</span><h3>ריקולים וסטטוס</h3><p>קריאות שירות שלא בוצעו ומידע על ביטול סופי</p></div><div><span>⌁</span><h3>נתוני דגם</h3><p>מפרט ונתוני WLTP, לצד מחיר יבואן לרכב חדש</p></div></div></>}
      {report && <div className="results" id="results">
        <div className="resultsHeader"><div><span className="eyebrow small">דוח רכב</span><h2>{vehicle ? `${value(vehicle, 'tozeret_nm')} ${value(vehicle, 'kinuy_mishari')}` : 'בדיקת רכב'}</h2><p>מידע ציבורי לפי מספר הרישוי שהוזן. הנתונים עשויים להיות חלקיים או להתעדכן במקור.</p></div><div className="plateBadge"><span>IL</span><strong dir="ltr">{plate}</strong></div></div>
        {hasResult && <div className="reportToolbar"><nav className="reportNav" aria-label="ניווט בדוח"><a href="#vehicle">פרטי הרכב</a><a href="#history">נסועה</a><a href="#ownership">בעלות</a><a href="#recalls">ריקולים</a><a href="#status">סטטוס</a></nav><a className="downloadButton" href={`/api/report?plate=${encodeURIComponent(plate!)}`} download={`AUTOPEEK-${plate}.pdf`}>↓ הורדת דוח PDF</a></div>}
        {!hasResult && <div className="card emptyState"><h2>לא נמצאו נתונים למספר הזה</h2><p>ייתכן שהרכב מחוץ לטווח הכיסוי של המאגרים, או שמספר הרישוי אינו נכון.</p></div>}
        {hasResult && <>
          {report.canceled && <div className="alert danger"><span>!</span><div><strong>נמצאה רשומה של ביטול סופי</strong><p>תאריך ביטול: {date(report.canceled.bitul_dt)}. יש לאמת סטטוס עדכני מול משרד התחבורה.</p></div></div>}
          {report.openRecalls.length > 0 && <div className="alert amber"><span>!</span><div><strong>{report.openRecalls.length} קריאות שירות מופיעות במאגר ריקולים שלא בוצעו</strong><p>כדאי לפנות ליבואן או למוסך מורשה לבירור ולטיפול.</p></div></div>}
          <div className="resultGrid"><div className="mainColumn">
            <Section id="vehicle" icon="▤" title="פרטי הרכב" subtitle="נתונים לפי מספר רישוי"><Status error={report.errors.vehicle} found={!!vehicle}/>{vehicle && <><Details row={vehicle} fields={[["tozeret_nm","יצרן"],["kinuy_mishari","שם מסחרי"],["degem_nm","קוד דגם"],["shnat_yitzur","שנת ייצור"],["ramat_gimur","רמת גימור"],["tzeva_rechev","צבע"],["sug_delek_nm","סוג דלק"],["baalut","סוג בעלות נוכחית"],["zmig_kidmi","צמיג קדמי"],["zmig_ahori","צמיג אחורי"],["moed_aliya_lakvish","עלייה לכביש"],["kvutzat_zihum","קבוצת זיהום"],["ramat_eivzur_betihuty","רמת אבזור בטיחותי"]]}/><div className="details"><Cell label="מועד טסט אחרון">{date(vehicle.mivchan_acharon_dt)}</Cell><Cell label="תוקף רישוי">{date(vehicle.tokef_dt)}</Cell></div>{report.extra && <div className="subblock"><h3>פרטים נוספים</h3><Details row={report.extra} fields={[["kod_omes_tzmig_kidmi","קוד עומס צמיג קדמי"],["kod_omes_tzmig_ahori","קוד עומס צמיג אחורי"],["kod_mehirut_tzmig_kidmi","קוד מהירות קדמי"],["kod_mehirut_tzmig_ahori","קוד מהירות אחורי"],["grira_nm","אבזור גרירה"]]}/></div>}</>}</Section>
            <Section id="history" icon="◷" title="נסועה ושינויי מבנה" subtitle="הנסועה דווחה בטסט האחרון בלבד"><Status error={report.errors.history} found={!!report.history} empty={<>לא פורסמה לרכב זה רשומה במאגר ההיסטוריה, ולכן אין לנו נתון נסועה או שינויי מבנה ממנו.{vehicle?.mivchan_acharon_dt && <> מועד הטסט האחרון במאגר הרכב: {date(vehicle.mivchan_acharon_dt)}.</>}</>}/>{report.history && <><div className="mileage"><span>נסועה בטסט האחרון</span><strong>{fmtNumber(report.history.kilometer_test_aharon)} <small>ק״מ</small></strong></div><div className="details"><Cell label="תאריך רישום ראשון">{date(report.history.rishum_rishon_dt)}</Cell><Cell label="מקוריות">{value(report.history, 'mkoriut_nm')}</Cell><Cell label="שינוי מבנה">{yesNo(report.history.shinui_mivne_ind)}</Cell><Cell label="גפ״מ">{yesNo(report.history.gapam_ind)}</Cell><Cell label="שינוי צבע">{yesNo(report.history.shnui_zeva_ind)}</Cell><Cell label="שינוי צמיגים">{yesNo(report.history.shinui_zmig_ind)}</Cell></div><p className="finePrint">זהו נתון יחיד מהטסט האחרון, ולא היסטוריית טיפולים או רצף מדידות נסועה.</p></>}</Section>
            <Section id="ownership" icon="♙" title="היסטוריית בעלות" subtitle="תאריכי רישום וסוגי בעלות; ללא שמות בעלים"><Status error={report.errors.ownership} found={report.ownership.length > 0} empty={<>לא פורסמה לרכב זה רשומת היסטוריית בעלות.{vehicle?.baalut && <> סוג הבעלות הנוכחית במאגר הרכב: {value(vehicle, 'baalut')}.</>} אין מכך להסיק שלא היו בעלים קודמים.</>}/>{report.ownership.length > 0 && <div className="timeline">{[...report.ownership].sort((a,b)=>Number(b.baalut_dt)-Number(a.baalut_dt)).map((r,i)=><div className="timelineItem" key={`${r._id}-${i}`}><span className="timelineDot"/><div><strong>{value(r,'baalut')}</strong><small>החל מ־{date(r.baalut_dt)}</small></div></div>)}</div>}</Section>
            <Section id="recalls" icon="◈" title="ריקולים שלא בוצעו" subtitle="רשומות פתוחות המופיעות במאגר לפי מספר רכב"><Status error={report.errors.openRecalls} found={report.openRecalls.length > 0} empty="לא נמצאה רשומה במאגר ריקולים שלא בוצעו. היעדר רשומה אינו אישור שאין ריקול אחר."/>{report.openRecalls.map((r,i)=><article className="recall" key={`${r.RECALL_ID}-${i}`}><div><span className="tag">{value(r,'SUG_RECALL')}</span><small>{date(r.TAARICH_PTICHA)}</small></div><h3>{value(r,'SUG_TAKALA')}</h3><p>{value(r,'TEUR_TAKALA')}</p><small>מספר קריאה: {value(r,'RECALL_ID')}</small></article>)}</Section>
          </div><aside className="sideColumn">
            <Section id="status" icon="◇" title="סטטוס ביטול"><Status error={report.errors.canceled} found={!!report.canceled} empty="לא נמצאה רשומת ביטול סופי במאגרים שנבדקו."/>{report.canceled && <div className="statusBox">ביטול סופי · {date(report.canceled.bitul_dt)}</div>}</Section>
            <Section id="model" icon="⌁" title="מפרט דגם ו־WLTP" subtitle="התאמה לפי קוד יצרן, קוד דגם ושנת ייצור"><Status error={report.errors.model} found={!!model}/>{model && <><Details row={model} fields={[["nefah_manoa","נפח מנוע (סמ״ק)"],["koah_sus","כוח סוס"],["mispar_moshavim","מושבים"],["merkav","מרכב"],["hanaa_nm","הנעה"],["technologiat_hanaa_nm","טכנולוגיית הנעה"],["CO2_WLTP","פליטת CO₂ WLTP (גרם/ק״מ)"],["madad_yarok","מדד ירוק"],["nikud_betihut","ציון בטיחות"]]}/><p className="finePrint">נתוני דגם עשויים להשתנות בין רמות גימור. מוצגת רשומת ההתאמה הראשונה.</p></>}</Section>
            <Section id="price" icon="₪" title="מחיר יבואן" subtitle="מחיר רכב חדש בעת דיווח היבואן"><Status error={report.errors.prices} found={!!price}/>{price && <><div className="price">₪{fmtNumber(price.mehir)}</div><p className="finePrint">{value(price,'shem_yevuan')} · שנת דגם {value(price,'shnat_yitzur')}. זה אינו שווי השוק של רכב משומש.</p></>}</Section>
            <div className="sideHint"><span>ⓘ</span><p>הודעות היצרנים על ריקולים אינן מקושרות ישירות למספר רישוי במאגר הציבורי. היעדר רשומה כאן אינו אישור שאין קריאת שירות לרכב.</p></div>
          </aside></div>
        </>}
      </div>}
      <section id="about" className="about"><div><span className="eyebrow small">לפני שמסתמכים על הדוח</span><h2>המידע עוזר לבדוק.<br/>הוא לא מחליף בדיקה.</h2></div><div><p>AUTOPEEK הוא שירות עצמאי המציג נתונים ממאגרים ציבוריים של משרד התחבורה. הוא אינו אתר ממשלתי ואינו פועל מטעם המדינה. זמינות הרשומות, דיוקן ומועד עדכונן תלויים במאגרים המקוריים.</p><p>היעדר רשומה אינו אישור לכך שאין ריקול, תאונה, שעבוד, בעלים קודמים או בעיה ברכב. לפני קנייה או החלטה כספית יש לאמת את הנתונים מול הגורמים המוסמכים ולבצע בדיקה מקצועית. דוח PDF משקף את המידע שהתקבל בזמן הפקתו בלבד.</p></div></section>
    </div><footer><div className="footerInner"><div className="footerBrand"><strong>AUTOPEEK</strong><span>© 2026 · שירות מידע עצמאי לרכב</span></div><div className="footerLinks"><a href="/terms">תנאי שימוש</a><a href="/privacy">פרטיות</a><a href="/accessibility">נגישות</a><a href="mailto:edgarzdv@gmail.com">יצירת קשר</a></div><p className="footerSource">מקור הנתונים: <a href="https://data.gov.il/he/organizations/ministry_of_transport" target="_blank" rel="noopener noreferrer">מאגרי משרד התחבורה באתר data.gov.il ↗</a></p></div></footer>
  </main>;
}
